### ISSUE TITLE
Most common RTP hostname string missing

### ISSUE THREAD

**Issue by daboross** [SystemsApproach/e2e#1]
Hi,

I'm unsure whether a GitHub issue is at all an appropriate form of feedback for this book. However, it's here, and seems pretty accessible. Reporting this since I've been really enjoying the book and its content! 

At the end of chapter 5.4, there seems to be an example of a hostname missing. Specifically, there's a line:

```
The most common format of the CNAME is , where host is the fully qualified domain name of the sending machine. Thus, an application launched by the user whose user name is jdoe running on the machine would use the string as its CNAME.
```

I expected there to be _something_ after the "CNAME is", and then again after "would use the string", but it's as if the two words appropriate for these locations disappeared.

For reference, the file I'm looking at is https://github.com/SystemsApproach/e2e/blob/fb612602ee602665d7c9e919d607b255b4e99d03/rtp.rst.

Thanks! And thanks for making this book, it's great.

**Comment by llpeterson** [comment]
Good catch. It's a typo introduced when I converted from the original LaTeX to ReStructured Text.

**Comment by llpeterson** [comment]
Fixed.
